using System;
using UnityEngine;
/*
information implementation.
*/
namespace AutoyaFramework {
	public partial class Autoya {

		/*
			public apis
		*/

		/**
			show markdown view which is generated by markdown data.
			then, if player touches button, link, or other items, selector will be raised.
		*/
		public static void Info_ConstructMarkdownView (string data, Action<GameObject> viewReceived, Action<int> selector) {
			Debug.Log("not yet implemented.");
		}
	}
}