using System;
using UnityEngine;
using AutoyaFramework.Information;
using System.Collections.Generic;

/*
	information implementation.
*/
namespace AutoyaFramework {
	public partial class Autoya {
		private InformationView info = new InformationView();

		/*
			public apis
		*/

		/**
			show information view which is generated by downloaded markdown data.
			then, if player touches button, link, or other items, something goes on.
		*/
		public static void Info_Show (string url, float windowWidth, float windowHeight, float anchorPos, Action<GameObject> view, Action<int, string> failed) {

			Debug.Assert(0 < windowWidth, "windowWidth is 0 or negative.");
			Debug.Assert(0 < windowHeight, "windowHeight is 0 or negative.");
			
			var http = new Connections.HTTP.HTTPConnection();

			var cor = http.Get(
				Guid.NewGuid().ToString(),
				new Dictionary<string, string>(),
				url,
				(conId, code, responseHeaders, data) => {
					var infoViewRootObject = autoya.info.Show(autoya.mainthreadDispatcher.Commit, data, new View(windowWidth, windowHeight, anchorPos));
					view(infoViewRootObject);
				},
				(conId, code, reason, responseHeaders) => {
					failed(code, reason);
				},
				5.0
			);

			autoya.mainthreadDispatcher.Commit(cor);			
		}
	}
}