/* DO NOT modify this file. This file is generated by GenerateBuildConfigTask */
namespace UnityEngine.UDP.Editor
{
    internal static class BuildConfig
    {
        public const string CLIENT_SECRET = "B63AFB324DE3D12A13827340019D1EE3";
        public const string ID_ENDPOINT = "https://id.unity.com";
        public const string CONSOLE_URL = "https://distribute.dashboard.unity.com";
        public const string UDP_ENDPOINT = "https://api-udp.unity.com";
        public const string CONNECT_ENDPOINT = "https://connect.unity.com";
        public const string CLIENT_ID = "channel_editor";
        public const string VERSION = "1.0.2";
        public const string API_ENDPOINT = "https://api.unity.com";
    }
}